Repository AY2425S2-CS2103T-T10-2/tp, pull requests merged in 2025-04, with the labels that each got.

#126 Authentication: Login on enter keypress
  src/main/java/seedu/address/ui/LoginDialog.java
  src/main/resources/view/LoginDialog.fxml
Labels: type.Enhancement, priority.Low, alpha-bug

#102 Command: unique prefix filter & status
  src/main/java/seedu/address/logic/parser/FilterStatusCommandParser.java
  src/main/java/seedu/address/logic/parser/SetStatusCommandParser.java
Labels: alpha-bug

#110 Command: CLI convention
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FilterStatusCommand.java
  src/main/java/seedu/address/logic/commands/SetStatusCommand.java
Labels: alpha-bug

#131 UserGuide: Updated
  docs/UserGuide.md
Labels: type.Enhancement

#134 Update UserGuide
  docs/UserGuide.md
  docs/images/LoginDialog.png
Labels: type.Bug

#122 Fix bug for findby empty argument
  src/main/java/seedu/address/logic/parser/FindByCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: alpha-bug

#152 Registration: Improve error messages
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CreateUserCommand.java
  src/main/resources/view/RegisterDialog.fxml
Labels: type.Bug, severity.High, alpha-bug

#119 Update import error message
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
Labels: alpha-bug

#127 Improve UI
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LoginDialog.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/RegisterDialog.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: type.Enhancement, priority.Medium, alpha-bug

#153 Bug: Fixed collapsing ListCells
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: alpha-bug

#167 Ui: Add minimum command box height
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.High

#168 Ui: Fix PersonCard responsive sizing
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Bug, severity.High

#169 Parser: Remove duplicated logic
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/exceptions/InvalidAccessRightsException.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: severity.High

#176 Ui: Standardise help window theme
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Enhancement, priority.Low

#177 HelpCommand-logged-out
  docs/UserGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
Labels: priority.Medium

#180 LandingPage: Fix broken link
  docs/index.md
Labels: type.Bug, severity.High

#239 Authentication: Restrict access to commands after logout
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/AuthenticateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Bug, severity.High

#237 Ui: Formatting long attribute values
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug, severity.Medium

#236 Change register to fit tp constraints
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AuthenticateCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/RegisterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/RegisterDialog.java
  src/main/resources/view/RegisterDialog.fxml
  src/test/java/seedu/address/logic/commands/AuthenticateCommandTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
Labels: Login Issues

#244 Ui: Fix tooltip typo
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Bug, severity.VeryLow

#245 SyntaxHighlighter: Handle white-space before commands gracefully
  src/main/java/seedu/address/ui/CommandSyntaxHighlighter.java
Labels: type.Bug, severity.Medium

#248 UserGuide: Addressing PE-D bugs
  docs/UserGuide.md
  docs/images/LoginDialogExample.png
  docs/images/RegisterDialogExample.png
  docs/images/StartUiLabelled.png
Labels: Documentation UG

#255 SyntaxHighlighter: Improve handling of white space before prefixed command
  src/main/java/seedu/address/ui/CommandSyntaxHighlighter.java
Labels: priority.Medium

#257 UserGuide: Update language to describe sample records
  docs/UserGuide.md
Labels: Documentation UG

#262 UserGuide: Release bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: Documentation DG, Documentation UG
