Repository AY2425S2-CS2103T-T10-2/tp, pull requests merged in 2025-03, with the labels that each got.

#31 Remove outstanding AB-3 reference
  docs/_config.yml
Labels: priority.High

#72 Add syntax highlighting
  build.gradle
  src/main/java/seedu/address/logic/commands/FindByCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterStatusCommandParser.java
  src/main/java/seedu/address/logic/parser/FindByCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/SetStatusCommandParser.java
  src/main/java/seedu/address/model/person/AttributeContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/CommandSyntaxHighlighter.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
Labels: type.Story, priority.Medium

#73 Add support for logout command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LogOutCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/resources/view/DarkTheme.css
Labels: type.Enhancement, priority.High

#82 Fonts: unicode fix
  src/main/java/seedu/address/ui/UnicodeIcons.java
Labels: type.Bug, severity.Low

#56 Hashing: admin password is safer
  src/main/java/seedu/address/commons/exceptions/HashingFunctionException.java
  src/main/java/seedu/address/commons/util/HasherUtil.java
  src/main/java/seedu/address/logic/commands/AuthenticateCommand.java
Labels: type.Enhancement, priority.Medium

#85 Add colour to status tags
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
Labels: type.Enhancement, priority.Low

#84 Add syntax highlights for logout
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/CommandSyntaxHighlighter.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Bug, priority.Medium

#87 Fix exception thrown by syntax highlighter when input box is empty
  src/main/java/seedu/address/ui/CommandSyntaxHighlighter.java
  src/test/java/seedu/address/ui/CommandSyntaxHighlighterTest.java
Labels: type.Bug, severity.High

#78 Role Based Access Control
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AuthenticateCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/AuthenticateException.java
  src/main/java/seedu/address/logic/commands/exceptions/InvalidAccessRightsException.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/LoginDialog.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AuthenticateCommandTest.java
Labels: type.Enhancement, priority.Medium
